site_name: All in one guide
site_url: https://angxddeep.github.io/All-in-one-guide/Home/
site_author: Angaddeep Singh
repo_url: https://github.com/Angxddeep/All-in-one-guide
repo_name: All in one guide

theme:
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.path
  - navigation.indexes
  - navigation.top
  - navigation.footer
  - search.suggest
  name: material
  favicon: images/logo.jpg
  logo: images/logo.jpg
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: teal
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: teal
    toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: 'Home.md'
  - Unlocking bootloader: 'Unlocking bootloader.md'
  - Rooting method: 'Root.md'
  - Flashing stock rom: 'Stock.md'
  - Unbrick Guide: 'Unbrick.md'
  
  # Additional configuration

extra:
  social:
  - icon: fontawesome/brands/x-twitter
    link: https://x.com/Angxddeep
  - icon: fontawesome/brands/mastodon
    link: https://mastodon.social/@angaddeep 
  - icon: fontawesome/brands/github
    link: https://github.com/Angxddeep
plugins:
  - search
