site_name: Flashing Custom Rom Guide
site_url: "https://deepangad.github.io/Custom-Rom-flashing-guide/index"
repo_url: https://github.com/deepangad/Custom-Rom-flashing-guide
repo_name: Custom Rom flashing guide
theme:
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.path
  - navigation.indexes
  - navigation.top
  name: material
  logo: images/logo.jpg
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: deep purple
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: deep purple
    toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
nav:
  - Geeting Started: 'Index.md'
  - Unlocking bootloader: 'Unlocking bootloader.md'
  - Rooting method: 'Root.md'
 

    