site_name: Flashing Custom Rom Guide
site_url: https://angxddeep.github.io/All-in-one-guide/
site_author: Angaddeep Singh
repo_url: https://github.com/deepangad/Custom-Rom-flashing-guide
repo_name: Custom Rom flashing guide
edit_uri: ""
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

theme:
  features:
  - navigation.instant
  - navigation.instant.progress
  - navigation.tabs
  - navigation.path
  - navigation.indexes
  - navigation.top
  name: material
  favicon: images/logo.jpg
  logo: images/logo.jpg
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    accent: orange
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    accent: orange
    toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
nav:
  - Home: 'Index.md'
  - Unlocking bootloader: 'Unlocking bootloader.md'
  - Rooting method: 'Root.md'
  - Flashing stock rom: 'Stock.md'
  - Unbrick Guide: 'Unbrick.md'
  
  # Additional configuration

extra:
  social:
  - icon: fontawesome/brands/twitter
    link: https://x.com/Angxddeep
  - icon: fontawesome/brands/github
    link: https://github.com/Angxddeep

